---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-config
data:
  WORDPRESS_DB_NAME: wordpress
  WORDPRESS_DB_USER: wordpress
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-wordpress-pass
type: Opaque
data:
  WORDPRESS_DB_PASSWORD: base64_encoded_wp_db_password
  MYSQL_ROOT_PASSWORD: base64_encoded_mysql_root_password
